include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    avoid_unnecessary_containers: false
    use_key_in_widget_constructors: false
    sized_box_for_whitespace: false
    prefer_const_literals_to_create_immutables: false